name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_FRONTEND: jusefdarwiche/frontend
      DOCKER_IMAGE_BACKEND: jusefdarwiche/backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t $DOCKER_IMAGE_FRONTEND:latest ./frontend
          docker push $DOCKER_IMAGE_FRONTEND:latest

      - name: Build and Push Backend Image
        run: |
          docker build -t $DOCKER_IMAGE_BACKEND:latest ./backend
          docker push $DOCKER_IMAGE_BACKEND:latest
